### ISSUE TITLE
Decide on using CamelCase, scheme-case or snake_case for properties

### ISSUE THREAD

**Issue by linkmauve** [ewilderj/doap#39]
Currently there is `Project`, `name`, `download-page`, `ArchRepository` and `foaf:mbox_sha1sum` all in a same document, it would be nice to avoid having to lookup the schema every time we want to write something. :)

**Comment by ewilderj** [comment]
RDF convention is CapitalizedCamel for classes, and lowercase for properties. DOAP convention is to use `kebab-case` for properties. The stuff from other namespaces, e.g. FOAF, we have no control over.

Because changing names in the schema is a breaking change, I'm unlikely to ever change any of this.
